import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from "next/script";
import {useRef} from "react";

export default function Home(props) {
    const result = useRef(null);

    const handleSubmit = (e) => {
        e.preventDefault();
        grecaptcha.ready(function () {
            grecaptcha.execute(props.siteKey, {action: 'submit'}).then(function (token) {
                // Add your logic to submit to your backend server here.
                verifyToken(token);
            });
        });
    }

    const verifyToken = (token) => {
        fetch(`/api/verify-token?token=${token}`, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
        }).then(r => r.json())
            .then(response => {
                const {success, score} = response;
                console.info('success', success)
                console.info('score', score)
                if (score > 0.5) { // use a threshold to verify user score. suppose I use 0.5 to determine that the user is human.
                    // Submit your form here.
                    result.current.innerHTML = `recaptcha verified with score ${score} and success ${success}`
                }
            }).catch(err => {
            console.error('error', err)
            result.current.innerHTML = "Error while verifying recaptcha token"
        })
    }

    return (
        <>
            <Script src={`https://www.google.com/recaptcha/api.js?render=${props.siteKey}`}></Script>
            <div className={styles.container}>

                <Head>
                    <title>Next.js reCAPTCHA</title>
                    <meta name={'author'} content={'Besmillah Ibrahimi'}/>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Add reCAPTCHA v3 in Next.js
                    </h1>

                    <form className={styles.grid} onSubmit={handleSubmit}>
                        <input type={'text'} name={'name'} placeholder={'enter your name'}/>
                        <input type={'email'} name={'email'} placeholder={'enter your email'}/>
                        <textarea name={'message'} placeholder={'type your message'}/>
                        <button type={'submit'}>Submit</button>
                    </form>

                    <h6 ref={result}></h6>
                </main>
            </div>
        </>
    )
}

export async function getServerSideProps() {
    return {
        props: {siteKey: process.env.RE_CAPTCHA_SITE_KEY}
    }
}
